Updating auto subscribe function
SumoLogic/sumologic-aws-lambda pull request #131
Opened 2021-02-25 11:06 UTC by SumoSourabh

adding license file, updating code and template to use destiantion arn along with rolearn

2021-02-25 11:16 UTC, himanshu219 commented on loggroup-lambda-connector/src/loggroup-lambda-connector.js
> +function subscribeToLambda(lambdaLogGroupName, destinationArn, roleArn, errorHandler) {
the function name is subscribeToLambda probably we can change it to subscribeLogGroupToService

2021-02-25 11:18 UTC, himanshu219 requested changes
actually all the sam related files should in sam folder can we move it to sam. I guess I forgot to commit that file.  Rest of the changes looks good to me.

2021-02-25 11:34 UTC, himanshu219 approved these changes

2021-04-01 06:05 UTC, himanshu219 requested changes

2021-04-01 06:07 UTC, SumoSourabh commented on loggroup-lambda-connector/src/loggroup-lambda-connector.js
> +    await logGroups.reduce(async (previousPromise, nextLogGroup) => {
Nop, I tried and it was working async.

2021-04-01 06:07 UTC, SumoSourabh commented on loggroup-lambda-connector/src/loggroup-lambda-connector.js
> +        await util.promisify(cwl.putSubscriptionFilter.bind(cwl))(params);
automatically available

2021-04-01 06:07 UTC, SumoSourabh commented on loggroup-lambda-connector/sam/packaged.yaml
> +  primerinvoke:
Sure

2021-04-01 06:09 UTC, SumoSourabh commented on loggroup-lambda-connector/src/loggroup-lambda-connector.js
> +        await subscribeExistingLogGroups(failedLogGroupNames, counter + 1);
Sure

2021-04-01 06:10 UTC, SumoSourabh commented on loggroup-lambda-connector/sam/template.yaml
> +    DeletionPolicy : "Retain"
The lambda is invoked again on deletion, which is not required.

2021-04-01 06:10 UTC, SumoSourabh commented on loggroup-lambda-connector/sam/template.yaml
> +        var response = require('cfn-response');
Yes, but it is only available using inline code. If we use it via src, then it is not available.

2021-04-01 06:13 UTC, himanshu219 commented
LGTM

2021-04-01 06:36 UTC, SumoSourabh commented on loggroup-lambda-connector/src/loggroup-lambda-connector.js
> +        await subscribeExistingLogGroups(failedLogGroupNames, counter + 1);
Changes done

2021-04-01 06:36 UTC, SumoSourabh commented on loggroup-lambda-connector/sam/packaged.yaml
> +  primerinvoke:
Changes done.

2021-04-01 06:37 UTC, merged