Added support to subscribe existing log groups by User defined Tags
SumoLogic/sumologic-aws-lambda pull request #208
Opened 2024-09-06 12:50 UTC by akhil-sumologic

2024-09-06 12:55 UTC, akhil-sumologic commented on loggroup-lambda-connector/src/loggroup-lambda-connector.js
> +        return new RegExp(pattern, "i");
I attempted to fix this, but it ended up changing the function's behaviour.

2024-09-09 06:36 UTC, himsharma01 approved these changes
lgtm

2024-09-09 06:37 UTC, himsharma01 requested changes
minor copy text commit

2024-09-09 06:48 UTC, akhil-sumologic commented on loggroup-lambda-connector/Readme.md
> +#### e.g
Done.

2024-09-09 06:49 UTC, himsharma01 approved these changes

2024-09-09 11:43 UTC, himsharma01 approved these changes
lgtm

2024-09-10 04:55 UTC, merged