Implemented AWS tag filters
SumoLogic/sumologic-aws-lambda pull request #210
Opened 2024-12-02 02:03 UTC by akhil-sumologic

2024-12-03 11:32 UTC, himsharma01 requested changes
lgtm

2024-12-03 11:32 UTC, himsharma01 commented on sumologic-app-utils/src/sumoresource.py
> +                print("limitToNamespaces: ", path["limitToNamespaces"])
Print can be removed

2024-12-03 11:32 UTC, himsharma01 commented on sumologic-app-utils/src/sumoresource.py
> +            if key in namespaces:
Lets only filter aws namespaces

2024-12-04 06:03 UTC, akhil-sumologic commented on sumologic-app-utils/src/sumoresource.py
> +            if key in namespaces:
Addressed

2024-12-05 09:37 UTC, himsharma01 approved these changes
lgtm

2024-12-05 10:26 UTC, himsharma01 approved these changes
lgtm

2024-12-05 12:14 UTC, himsharma01 approved these changes
lgtm

2024-12-06 07:18 UTC, merged